name=input("Enter you name- ")
age=input("Enter your age- ")
goal=input("Enter your goal-" )
sleep=input("Enter you sleep goal- ")
print("--Your Vega Profile--")
print("Name: ",name)
print("Age: ",age)
print("Goal: ",goal)
print("Sleep: ",sleep)